name: lintme
version: 1.0.0
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://lintme.dev/
repository: https://github.com/ricardodalarme/lintme
issue_tracker: https://github.com/ricardodalarme/lintme/issues
documentation: https://lintme.dev/docs/individuals/getting-started/

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: ">=5.13.0 <5.14.0"
  analyzer_plugin: ">=0.11.0 <0.12.0"
  ansicolor: ^2.0.2
  args: ^2.5.0
  collection: ^1.19.0
  crypto: ^3.0.3
  file: ^7.0.0
  glob: ^2.1.2
  html: ">=0.15.0 <0.16.0"
  http: ^1.2.1
  lintme_presets: ^1.0.1
  meta: ^1.15.0
  path: ^1.9.0
  platform: ^3.1.5 # overridden for lowest versions compatibility
  pub_updater: ^0.4.0
  source_span: ^1.10.0
  uuid: ^4.4.0
  xml: ">=6.0.0 <8.0.0"
  yaml: ^3.1.2

dev_dependencies:
  coverage: ^1.8.0
  intl: ">=0.19.0 <0.20.0"
  lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.25.7

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
