name: dart_code_metrics_plugin_loader
description: This pubspec determines the version of the analyzer plugin to load.
version: 5.7.5
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_code_metrics:
    path: ./../../

dev_dependencies:
  lints: ^4.0.0
