name: Toolkit InnerSource-OpenSource
on: workflow_dispatch
jobs:
  build-repo:
    runs-on: ubuntu-latest
    name: Download tools and templates Innersource-Opensource
    steps:
      - name: Generate a Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID_ADMIN_GITHUB }}
          private_key: ${{ secrets.APP_PRIVATE_KEY_ADMIN_GITHUB }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - id: TestToolkit
        uses: bancolombia/opensource-innersource-toolkit@main
        with:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          TYPE_REPOSITORY: 'innersource'
          USERS_REVIEWERS: '@santitigaga @ajtortolero'
          TEMPLATE_LANGUAGE: 'EN'
